version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules/
    command: npm run start:debug
    depends_on: 
      - mysql
    environment:
      MONGO_URL: root:pass12345@localhost
    # networks:
    #   - server-network      
    ports:
      - 3000:3000
      - 9229:9229
  # mongodb:
  #   image: mongo:5.0.0
  #   container_name: server-mongodb
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=pass12345
  #   # networks:
  #   #   - server-network
  #   ports:
  #     - 27017:27017
  #   healthcheck:
  #     test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   restart: unless-stopped
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  spa:
    build:
      dockerfile: Dockerfile
      context: ./spa
      target: development
    command: npm run start
    volumes:
      - ./spa:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - api  
    # networks:
    #   - server-network  
# networks:
#   server-network: