 
default:
  type: mysql #=TYPEORM_CONNECTION
  driver: {} #THIS'LL FORCE TO mysql2
  host: localhost #=TYPEORM_HOST
  port: 3306 #=TYPEORM_PORT
  username: xxxx #=TYPEORM_USERNAME
  password: xxxxx #=TYPEORM_PASSWORD
  database: xxx #=TYPEORM_DATABASE
  entities: #=TYPEORM_ENTITIES
    - dist/**/*.entity.js
  migrations: #=TYPEORM_MIGRATIONS
    - migration/*.js
  cli:
    migrationsDir: migration #=TYPEORM_MIGRATIONS_DIR